### ISSUE TITLE
[server] 개발 스펙 정리

### ISSUE THREAD

**Issue by Junhyeon2** [9trees/youngest-server#1]
필요한 부분 댓글 달아주고 TL이 다음 모임 전까지 정리
(이 댓글 수정하여 정리)

**Comment by kwonjunbeom** [comment]
스프링부트, 스프링시큐리티, 젠킨스, 그래들

**Comment by Junhyeon2** [comment]
- 배포: docker
- 웹 서버: nginx
- 서버: Spring Boot + JPA + Hibernate
- 통계: Apache Druid
- 모니터링: elastic search + kibana

**Comment by SeoJeongHan** [comment]
이왕 이면 버전 까지 명시 해줄수 있는건 버전까지 명시 바람

**Comment by SeoJeongHan** [comment]
추가 의견에 대한 지속적인 업데이트 및 추후 spec 확정 예정

1. 배포
- Docker

2. 웹 서버
- Nginx
- Aphache ( ver. 7?8?)

3. was 서버
- Spring Boot ( ver. 2? ) + JPA + Spring security

4. 모니터링
- Pinpoint

5. 통계
- ELK

6. 배치
- Jenkins

7. DB
- MariaDB
- Mysql

8. 빌드툴
- Gradle
- Maven

**Comment by BokDaHoon** [comment]
1. 빌드툴
- npm, gulp
2. 번들링 툴
- webpack4
3. 보일러 플레이트
- expo대신 react-native-cli 사용
4. 소스 품질 개선 도구
- lint, prettier
5. 필수 써드파티 라이브러리
- babel, redux, redux-thunk

**Comment by Junhyeon2** [comment]
MSA, Spring Cloud 도움 되는 영상
- https://tv.naver.com/v/3925308
- https://tv.naver.com/v/3925399
